#!/usr/bin/env tsx
// Generates src/data/vocabulary.ts from the HuggingFace dataset
// Thoria/mandarin-most-common-words-tr-en. Run manually via `npm run sync-vocab`.

import fs from 'node:fs';
import path from 'node:path';

const DATASET = 'Thoria/mandarin-most-common-words-tr-en';
const CONFIG  = 'default';
const SPLIT   = 'train';
const PAGE    = 100;
const API     = 'https://datasets-server.huggingface.co/rows';

type HFRow = Record<string, unknown>;

type AudioPair = { normal: string; slow: string };
type AudioNest = {
  hanzi?: AudioPair;
  english?: AudioPair;
  turkish?: AudioPair;
  example_zh?: AudioPair;
  example_en?: AudioPair;
  example_tr?: AudioPair;
};

const AUDIO_COLS: Array<[keyof AudioNest, string, string]> = [
  ['hanzi',      'audio_hanzi_normal',      'audio_hanzi_slow'],
  ['english',    'audio_english_normal',    'audio_english_slow'],
  ['turkish',    'audio_turkish_normal',    'audio_turkish_slow'],
  ['example_zh', 'audio_example_zh_normal', 'audio_example_zh_slow'],
  ['example_en', 'audio_example_en_normal', 'audio_example_en_slow'],
  ['example_tr', 'audio_example_tr_normal', 'audio_example_tr_slow'],
];

function buildAudio(row: HFRow): AudioNest | undefined {
  const nest: AudioNest = {};
  for (const [key, nCol, sCol] of AUDIO_COLS) {
    const n = row[nCol];
    const s = row[sCol];
    if (typeof n === 'string' && typeof s === 'string' && n && s) {
      nest[key] = { normal: n, slow: s };
    }
  }
  return Object.keys(nest).length ? nest : undefined;
}

function stripNullish<T extends object>(obj: T): Partial<T> {
  const out: Partial<T> = {};
  for (const [k, v] of Object.entries(obj)) {
    if (v !== undefined && v !== null && v !== '') (out as any)[k] = v;
  }
  return out;
}

function rowToVocab(row: HFRow) {
  const base = stripNullish({
    hanzi:      row.hanzi,
    pinyin:     row.pinyin,
    turkish:    row.turkish,
    english:    row.english,
    example_zh: row.example_zh,
    example_tr: row.example_tr,
    example_en: row.example_en,
    category:   row.category,
  });
  const audio = buildAudio(row);
  return audio ? { ...base, audio } : base;
}

export function rowsToVocabularyTs(rows: HFRow[]): string {
  const records = rows.map(rowToVocab);
  const body = JSON.stringify(records, null, 2);
  return `// AUTO-GENERATED by scripts/sync-vocab.ts — do not edit by hand.
// Source: HuggingFace dataset ${DATASET}.
// Regenerate: \`npm run sync-vocab\`.

export interface VocabularyAudio {
  normal: string;
  slow: string;
}

export interface VocabularyWord {
  hanzi: string;
  pinyin: string;
  turkish: string;
  english?: string;
  example_zh?: string;
  example_tr?: string;
  example_en?: string;
  category: string;
  audio?: {
    hanzi?:      VocabularyAudio;
    english?:    VocabularyAudio;
    turkish?:    VocabularyAudio;
    example_zh?: VocabularyAudio;
    example_en?: VocabularyAudio;
    example_tr?: VocabularyAudio;
  };
}

export const VOCABULARY: VocabularyWord[] = ${body};
`;
}

async function fetchAllRows(): Promise<HFRow[]> {
  const all: HFRow[] = [];
  let offset = 0;
  while (true) {
    const url = `${API}?dataset=${encodeURIComponent(DATASET)}&config=${CONFIG}&split=${SPLIT}&offset=${offset}&length=${PAGE}`;
    const res = await fetch(url);
    if (!res.ok) throw new Error(`HF API returned ${res.status}: ${await res.text()}`);
    const json = await res.json() as { rows: Array<{ row_idx: number; row: HFRow }>; num_rows_total: number };
    if (!json.rows?.length) break;
    for (const r of json.rows) all.push(r.row);
    offset += json.rows.length;
    if (offset >= (json.num_rows_total ?? 0)) break;
  }
  return all;
}

async function main() {
  console.log(`Fetching rows from ${DATASET}...`);
  const rows = await fetchAllRows();
  console.log(`Received ${rows.length} rows.`);
  const out = rowsToVocabularyTs(rows);
  const target = path.join(process.cwd(), 'src', 'data', 'vocabulary.ts');
  fs.writeFileSync(target, out);
  console.log(`Wrote ${target} (${out.length} bytes).`);
}

const invokedDirectly = typeof process !== 'undefined' && process.argv[1]?.endsWith('sync-vocab.ts');
if (invokedDirectly) {
  main().catch(err => {
    console.error(err);
    process.exit(1);
  });
}
